### ISSUE TITLE
希望作者大大出个调用sd api的教程

### ISSUE THREAD

**Issue by PAIZ1999** [wenda-LLM/wenda#235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ImmNaruto** [comment]
修改plugins/zhishuku_agents.py中的sd_agent接口方法 把里面的url改成部署好sd的api

**Comment by lindiny** [comment]
> 

好像还是不行，有人解决了没

**Comment by zhuang-maowei** [comment]
config.yml 里面加上sd的地址就行了，参考下面
```
library:
   agents:
      # SD图像地址
      sd_host: "http://127.0.0.1:17862"
```
送生成的小妹妹图片一张
![image](https://github.com/wenda-LLM/wenda/assets/59003887/0757b003-9011-4673-a877-6576831d1fdf)
