### ISSUE TITLE
在闻达笔记、闻达论文等界面，只显示界面的上半部分（火狐浏览器不适配）

### ISSUE THREAD

**Issue by timothy-WangS** [wenda-LLM/wenda#548]
![Image](https://github.com/user-attachments/assets/6578b96a-8540-4d50-add5-0b68299deb05)

**Comment by l15y** [comment]
加这么一个样式
```css
#app{
  height: 100%;
}
```
